version: '2'
services:
  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
  odoo10:
    image: odoo:10.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
    environment:
        - HOST=db
        - USER=$POSTGRES_PASSWORD
        - PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./o_addons:/mnt/extra-addons
      - ./o_etc:/etc/odoo
      - odoo_data:/var/lib/odoo/
volumes:
  db:
  odoo10:
  odoo_data:
  pg_data:
